apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: voting-sqlserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: voting-sqlserver
    spec:
      containers:
      - name: voting-sqlserver
        image: microsoft/mssql-server-linux
        ports:
        - containerPort: 1433
          name: redis
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: Microsoft123!
        - name: MSSQL_PID
          value: Developer
---
apiVersion: v1
kind: Service
metadata:
  name: voting-sqlserver
spec:
  ports:
  - port: 1433
  selector:
    app: voting-sqlserver
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: voting-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: voting-web
    spec:
      containers:
      - name: voting-web
        image: erjosito/centos_httpd_php
        ports:
        - containerPort: 80
        env:
        - name: SQLSERVER
          value: "voting-sqlserver"
---
apiVersion: v1
kind: Service
metadata:
  name: voting-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: voting-web